development:
  dialect: postgres
  datasource: host=host.docker.internal port=5432 user=postgres password=123456 dbname=footcerdb sslmode=disable
  dir: migrations
  table: migrations
#development:
#  dialect: postgres
#  datasource: host=35.184.70.223 port=5432 user=footcerdb password=PMa45PqnMHiHCn40 dbname=footcerdb sslmode=disable
#  dir: migrations
#  table: migrations
